### PR TITLE
PR for Newsweek Working Branch

### PR DESCRIPTION
**Pull request by collinsugwu**
What this PR does
1. Makes the site responsive using bootstrap
2.structure contents in their different positions

### CODE REVIEW

**Review by uche-inyama — CHANGES_REQUESTED** [review]
## Hi collins! nice job,

But there are updates you need to make :slightly_smiling_face: 

- [ ] There are no linter checks in this project, kindly implement it.

- [ ] Wrap the main contents of your html document inside the ```main tag``` for semantic html.

- [ ] In your footer section, your copy right and date are not properly aligned.

#### After implementing these changes submit another form for a code review

#### ``` Have a great day ``` :slightly_smiling_face:

**Review by stratospherique — CHANGES_REQUESTED** [review]
> ### Pull request under review by Ahmed Mahfoudh TSE
### Great work :clap: . However, you didn't apply some of the suggested changes as you should. check below :arrow_down: 

- **{REQUIRED]** `<main>`, `<header>` and `<footer>` are independent, they can't be wrapped inside each other.

- **{REQUIRED]** My colleague hinted about the issue below :arrow_down: . :pray: fix it.
image

### That's it :relaxed: When finished, kindly resubmit another code review request :pray:

**Comment by collinsugwu** [comment]
> > ### Pull request under review by Ahmed Mahfoudh TSE
> 
> ### Great work 👏 . However, you didn't apply some of the suggested changes as you should. check below ⬇️
> * **{REQUIRED]** `<main>`, `<header>` and `<footer>` are independent, they can't be wrapped inside each other.
> * **{REQUIRED]** My colleague hinted about the issue below ⬇️ . 🙏 fix it.
>   image
> 
> ### That's it ☺️ When finished, kindly resubmit another code review request 🙏

**Review by stratospherique — APPROVED** [review]
### Great job implementing the suggested changes :clap: . Your project is approved :heavy_check_mark: and you can merge to master :+1: :+1:

**Pull request merged**
